pipeline:
  backend:
    image: golang
    commands:
      - go get
      - go build
      - go test

  frontend:
    image: node:6
    commands:
      - npm install
      - npm test

  notify:
    image: drillster/drone-email
    host: smtp.exmail.qq.com
    username: app@deltaentropy.com
    password: 7jiong@APP
    from: app@deltaentropy.com
    recipients: [ zhoufp@deltaentropy.com ]
    recipients_only: true
    when:
      status: [ changed, failure ]
